const KEY='lxst.identity.v2',CHAT_KEY='lxst.chats.v1',FLAGS_KEY='lxst.flags.v1';
const iceServers=[{urls:'stun:stun.l.google.com:19302'}];
const $=s=>document.querySelector(s);
const state={id:null,tab:'radio',tx:false,latch:false,logs:[],heard:[],stations:[],selected:null,directed:null,chats:{},flags:{},installEvt:null,mesh:null,lastTap:0,sweep:0};
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
const shortHash=h=>`${h.slice(0,8)}…${h.slice(-6)}`;
const stamp=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function log(line){state.logs=[`${stamp()}  ${line}`,...state.logs].slice(0,40);renderLog();}
function hashNum(s,i=0){let h=2166136261^i;for(let c=0;c<s.length;c++)h=Math.imul(h^s.charCodeAt(c),16777619);return (h>>>0)/4294967295;}
async function hashSeed(seed){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('lxst:'+seed));return hex(new Uint8Array(d)).slice(0,32);}
async function loadIdentity(){try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(p.seed&&p.hash)return p;}}catch{}
const seed=hex(crypto.getRandomValues(new Uint8Array(16)));const hash=await hashSeed(seed);
const id={name:'LXST-'+hash.slice(0,4).toUpperCase(),seed,hash};localStorage.setItem(KEY,JSON.stringify(id));return id;}
function loadChats(){try{state.chats=JSON.parse(localStorage.getItem(CHAT_KEY)||'{}');}catch{state.chats={};}}
function saveChats(){localStorage.setItem(CHAT_KEY,JSON.stringify(state.chats));}
function loadFlags(){try{state.flags=JSON.parse(localStorage.getItem(FLAGS_KEY)||'{}');}catch{state.flags={};}}
function saveFlags(){localStorage.setItem(FLAGS_KEY,JSON.stringify(state.flags));}
function flag(hash){return state.flags[hash]||{pin:false,mute:false,watch:false};}
const NAMES=['NETTLE','BRAMBLE','FEN','CAIRN','SKERRY','MOSS','TOR','WOLD'];
function seedGhosts(selfHash){return NAMES.map((name,i)=>{const h=hashNum(selfHash,i+3);const a=h*Math.PI*2;const r=0.28+hashNum(selfHash,i+11)*0.55;const hash=(name+selfHash).replace(/[^a-f0-9]/gi,'a').slice(0,8)+hex(crypto.getRandomValues(new Uint8Array(4)));return{hash:hash.slice(0,32).padEnd(32,'0'),name,kind:'heard',ghost:true,x:0.5+Math.cos(a)*r*0.42,y:0.5+Math.sin(a)*r*0.42,last:Date.now()-Math.floor(h*400000),rssi:Math.round(-40-h*50)};});}
function placePeer(st){const a=hashNum(st.hash)*Math.PI*2;const r=0.22+hashNum(st.hash,7)*0.5;st.x=0.5+Math.cos(a)*r*0.42;st.y=0.5+Math.sin(a)*r*0.42;return st;}
let actx,osc,gain,mic;
async function ensureAudio(){if(!actx)actx=new AudioContext();if(actx.state==='suspended')await actx.resume();return actx;}
function stopTone(){try{osc?.stop();}catch{}osc?.disconnect();gain?.disconnect();osc=gain=null;}
async function startTx(){const audio=await ensureAudio();stopTone();gain=audio.createGain();gain.gain.value=0.035;gain.connect(audio.destination);osc=audio.createOscillator();osc.frequency.value=920;osc.type='sine';osc.connect(gain);osc.start();try{mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});}catch{mic=null;}}
function stopTx(){stopTone();mic?.getTracks().forEach(t=>t.stop());mic=null;}
function waitIce(pc){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(res=>{const t=setTimeout(res,2500);pc.onicegatheringstatechange=()=>{if(pc.iceGatheringState==='complete'){clearTimeout(t);res();}};});}
function createMesh(localHash){const pc=new RTCPeerConnection({iceServers});let channel=null;const bind=()=>{if(!channel)return;channel.onopen=()=>{log('channel open');channel.send(JSON.stringify({kind:'hello',hash:localHash,name:state.id.name}));};channel.onmessage=ev=>{try{const msg=JSON.parse(String(ev.data));if(msg.kind==='hello'&&msg.hash)hear(msg.hash,msg.name);if(msg.kind==='ptt')log(`PTT ${msg.state} from ${String(msg.hash).slice(0,8)}`);if(msg.kind==='chat'&&msg.hash){pushMsg(msg.hash,{from:'them',text:msg.text,t:Date.now()});log('msg from '+String(msg.hash).slice(0,8));}}catch{log(String(ev.data));}};};pc.ondatachannel=ev=>{channel=ev.channel;bind();};pc.onconnectionstatechange=()=>log('link '+pc.connectionState);return{async createInvite(){channel=pc.createDataChannel('lxst');bind();const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);return JSON.stringify({type:'offer',from:localHash,payload:pc.localDescription});},async acceptInvite(raw){const signal=JSON.parse(raw);await pc.setRemoteDescription(signal.payload);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitIce(pc);return JSON.stringify({type:'answer',from:localHash,payload:pc.localDescription});},async applyAnswer(raw){const signal=JSON.parse(raw);await pc.setRemoteDescription(signal.payload);},sendPtt(on){if(channel?.readyState==='open')channel.send(JSON.stringify({kind:'ptt',state:on?'TX':'RX',hash:localHash,to:state.directed}));},sendChat(to,text){if(channel?.readyState==='open'){channel.send(JSON.stringify({kind:'chat',hash:localHash,to,text}));return true;}return false;},close(){channel?.close();pc.close();}};}
function hear(hash,name){const existing=state.stations.find(s=>s.hash===hash);if(existing){existing.last=Date.now();existing.ghost=false;if(name)existing.name=name;}else{state.stations.push(placePeer({hash,name:name||('PEER-'+hash.slice(0,4).toUpperCase()),kind:'peer',ghost:false,last:Date.now(),rssi:-52}));}state.heard=[{hash,last:Date.now()},...state.heard.filter(h=>h.hash!==hash)].slice(0,12);renderHeard();renderThreads();}
function stationByHash(hash){return state.stations.find(s=>s.hash===hash);}
function pushMsg(hash,msg){if(!state.chats[hash])state.chats[hash]={unread:0,msgs:[]};state.chats[hash].msgs.push(msg);if(msg.from==='them'&&state.selected?.hash!==hash)state.chats[hash].unread+=1;saveChats();if(!$('#chat-win').hidden&&state.selected?.hash===hash)renderMsgs(hash);renderThreads();}
async function setTalk(on){state.tx=on;$('#ptt').classList.toggle('hot',on);$('#ptt-label').textContent=on?'TX':'PTT';if(on){await startTx();state.mesh?.sendPtt(true);log(state.directed?`TX → ${shortHash(state.directed)}`:'TX open');}else{stopTx();state.mesh?.sendPtt(false);log('RX');}renderBars();}
function onPttDown(){const now=Date.now();if(now-state.lastTap<280){state.latch=!state.latch;$('#ptt-cap').textContent=state.latch?'LATCHED':'HOLD / DBL TAP';setTalk(state.latch);}else if(!state.latch)setTalk(true);state.lastTap=now;}
function onPttUp(){if(!state.latch)setTalk(false);}
function setTab(tab){state.tab=tab;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('[data-panel]').forEach(p=>{p.hidden=p.dataset.panel!==tab;});if(tab==='mesh')resizeRadar();if(tab==='chat')renderThreads();}
function renderLog(){$('#log').innerHTML=state.logs.slice(0,6).map(l=>`<div>${escapeHtml(l)}</div>`).join('');}
function renderHeard(){const el=$('#heard');if(!el)return;const live=state.stations.filter(s=>!s.ghost);if(!live.length){el.innerHTML='<div class="muted">Ghosts on radar are nearby-heard simulations until a real link.</div>';return;}el.innerHTML=live.map(h=>`<div class="row" data-open="${h.hash}"><span>${h.name} ${shortHash(h.hash)}</span><span class="muted">live</span></div>`).join('');}
function renderBars(){const n=state.tx?4:state.heard.length?3:2;$('#bars').innerHTML=[1,2,3,4].map(i=>`<i class="${i<=n?'on':''}" style="height:${3+i*2}px"></i>`).join('');}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderThreads(){const el=$('#thread-list');if(!el)return;const rows=Object.keys(state.chats).map(hash=>{const st=stationByHash(hash);const msgs=state.chats[hash].msgs;const last=msgs[msgs.length-1];return{hash,name:st?.name||shortHash(hash),last,unread:state.chats[hash].unread||0};}).sort((a,b)=>(b.last?.t||0)-(a.last?.t||0));if(!rows.length){el.innerHTML='<div class="muted">No threads yet. Tap a station on mesh to open chat.</div>';return;}el.innerHTML=rows.map(r=>`<button class="thread" data-open="${r.hash}" type="button"><div><strong>${escapeHtml(r.name)}</strong><div class="preview">${escapeHtml(r.last?.text||'')}</div></div><div>${r.unread?`<span class="unread">${r.unread}</span>`:''}</div></button>`).join('');}
function renderMsgs(hash){const box=$('#msgs');const msgs=state.chats[hash]?.msgs||[];box.innerHTML=msgs.map(m=>`<div class="bubble ${m.from}"><div>${escapeHtml(m.text)}</div><time>${new Date(m.t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>`).join('');box.scrollTop=box.scrollHeight;}
function openSheet(st){state.selected=st;$('#sheet').hidden=false;$('#sheet-name').textContent=st.name;$('#sheet-hash').textContent=shortHash(st.hash);$('#sheet-kind').textContent=st.ghost?'simulated contact':'linked station';const f=flag(st.hash);$('#sheet-meta').textContent=[`${st.rssi} dBm`,f.pin?'pinned':'',f.mute?'muted':'',f.watch?'watched':''].filter(Boolean).join(' · ');$('[data-act="pin"]').textContent=f.pin?'Unpin':'Pin';$('[data-act="mute"]').textContent=f.mute?'Unmute':'Mute';$('[data-act="watch"]').textContent=f.watch?'Unwatch':'Watch';}
function closeSheet(){$('#sheet').hidden=true;}
function openChat(st){state.selected=st;if(!state.chats[st.hash])state.chats[st.hash]={unread:0,msgs:[]};state.chats[st.hash].unread=0;saveChats();$('#chat-title').textContent=st.name;$('#chat-sub').textContent=shortHash(st.hash);$('#chat-win').hidden=false;renderMsgs(st.hash);renderThreads();if(st.ghost&&state.chats[st.hash].msgs.length===0){setTimeout(()=>{pushMsg(st.hash,{from:'them',text:`${st.name} copies. Text is store-and-forward until a live link.`,t:Date.now()});},600);}}
function resizeRadar(){const c=$('#radar');const size=Math.min(c.parentElement.clientWidth,360);const dpr=Math.min(window.devicePixelRatio||1,2);c.width=size*dpr;c.height=size*dpr;c.style.width=size+'px';}
function drawRadar(){const c=$('#radar');const g=c.getContext('2d');const w=c.width,h=c.height,cx=w/2,cy=h/2,r=Math.min(w,h)/2-4;g.clearRect(0,0,w,h);g.fillStyle='#07110c';g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.fill();g.strokeStyle='rgba(61,255,138,0.18)';g.lineWidth=1;for(let i=1;i<=4;i++){g.beginPath();g.arc(cx,cy,(r*i)/4,0,Math.PI*2);g.stroke();}g.beginPath();g.moveTo(cx-r,cy);g.lineTo(cx+r,cy);g.moveTo(cx,cy-r);g.lineTo(cx,cy+r);g.stroke();g.save();g.translate(cx,cy);g.rotate(state.sweep);const lg=g.createLinearGradient(0,0,r,0);lg.addColorStop(0,'rgba(61,255,138,0)');lg.addColorStop(1,'rgba(61,255,138,0.28)');g.fillStyle=lg;g.beginPath();g.moveTo(0,0);g.arc(0,0,r,-0.35,0.02);g.closePath();g.fill();g.restore();g.fillStyle='#3dff8a';g.beginPath();g.arc(cx,cy,Math.max(4,w*0.012),0,Math.PI*2);g.fill();for(const st of state.stations){const f=flag(st.hash);if(f.mute)continue;const x=st.x*w,y=st.y*h,sel=state.selected?.hash===st.hash;g.fillStyle=st.ghost?'#7f9a86':'#3dff8a';if(f.pin)g.fillStyle='#ffb020';if(sel)g.fillStyle='#ffffff';g.beginPath();g.arc(x,y,sel?7:5,0,Math.PI*2);g.fill();if(f.watch){g.strokeStyle='rgba(61,255,138,0.7)';g.beginPath();g.arc(x,y,11,0,Math.PI*2);g.stroke();}g.fillStyle='rgba(215,234,217,0.85)';g.font=`${Math.max(10,w*0.028)}px ui-sans-serif`;g.textAlign='center';g.fillText(st.name,x,y-10);}}
function hitStation(ev){const c=$('#radar');const rect=c.getBoundingClientRect();const x=(ev.clientX-rect.left)/rect.width;const y=(ev.clientY-rect.top)/rect.height;let best=null,bestD=0.06;for(const st of state.stations){const d=Math.hypot(st.x-x,st.y-y);if(d<bestD){bestD=d;best=st;}}return best;}
async function makeInvite(){const raw=await state.mesh.createInvite();$('#invite').value=raw;try{await navigator.clipboard.writeText(raw);log('invite copied');}catch{log('invite ready');}}
async function applyPaste(){const raw=$('#paste').value.trim();if(!raw)return;try{const parsed=JSON.parse(raw);if(parsed.type==='offer'){const ans=await state.mesh.acceptInvite(raw);$('#invite').value=ans;try{await navigator.clipboard.writeText(ans);}catch{}log('answer copied — send back');}else{await state.mesh.applyAnswer(raw);log('answer applied');}}catch{log('bad handshake');}}
function updateDirectLine(){const el=$('#direct-line');if(!state.directed){el.textContent='Broadcast · all heard';return;}const st=stationByHash(state.directed);el.textContent='Directed · '+(st?.name||shortHash(state.directed));}
async function main(){state.id=await loadIdentity();loadChats();loadFlags();state.stations=seedGhosts(state.id.hash);$('#call').textContent=shortHash(state.id.hash);$('#fullhash').textContent=state.id.hash;$('#idname').textContent=state.id.name;state.mesh=createMesh(state.id.hash);log('station '+shortHash(state.id.hash)+' ready');
const tick=()=>{$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});};tick();setInterval(tick,15000);renderBars();renderHeard();renderThreads();
$('#ptt').addEventListener('pointerdown',onPttDown);$('#ptt').addEventListener('pointerup',onPttUp);$('#ptt').addEventListener('pointercancel',onPttUp);
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
$('#btn-invite').addEventListener('click',makeInvite);$('#btn-apply').addEventListener('click',applyPaste);
$('#btn-link').addEventListener('click',()=>$('#link-modal').hidden=false);$('#link-close').addEventListener('click',()=>$('#link-modal').hidden=true);
$('#sheet-close').addEventListener('click',closeSheet);$('#sheet').addEventListener('click',e=>{if(e.target.id==='sheet')closeSheet();});
$('#chat-back').addEventListener('click',()=>{$('#chat-win').hidden=true;});
document.querySelector('.sheet-grid').addEventListener('click',async e=>{const act=e.target.dataset.act;const st=state.selected;if(!act||!st)return;const f=flag(st.hash);if(act==='chat'){closeSheet();openChat(st);}else if(act==='ptt'){state.directed=state.directed===st.hash?null:st.hash;updateDirectLine();closeSheet();setTab('radio');log(state.directed?`directed PTT ${st.name}`:'back to broadcast');}else if(act==='pin'){f.pin=!f.pin;state.flags[st.hash]=f;saveFlags();openSheet(st);}else if(act==='mute'){f.mute=!f.mute;state.flags[st.hash]=f;saveFlags();openSheet(st);}else if(act==='watch'){f.watch=!f.watch;state.flags[st.hash]=f;saveFlags();openSheet(st);}else if(act==='copy'){try{await navigator.clipboard.writeText(st.hash);log('id copied');}catch{log(st.hash);}}});
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const text=$('#chat-input').value.trim();if(!text||!state.selected)return;$('#chat-input').value='';pushMsg(state.selected.hash,{from:'me',text,t:Date.now()});const live=state.mesh?.sendChat(state.selected.hash,text);if(!live&&state.selected.ghost){setTimeout(()=>{const replies=['Copy.','Stand by.','On frequency.','Roger — will QSL later.','Weak but readable.'];pushMsg(state.selected.hash,{from:'them',text:replies[Math.floor(Math.random()*replies.length)],t:Date.now()});},700+Math.random()*900);}});
$('#thread-list').addEventListener('click',e=>{const btn=e.target.closest('[data-open]');if(!btn)return;const st=stationByHash(btn.dataset.open)||{hash:btn.dataset.open,name:shortHash(btn.dataset.open),ghost:true};openChat(st);});
$('#heard').addEventListener('click',e=>{const row=e.target.closest('[data-open]');if(!row)return;const st=stationByHash(row.dataset.open);if(st)openSheet(st);});
$('#radar').addEventListener('click',e=>{const st=hitStation(e);if(st)openSheet(st);});
$('#btn-rename').addEventListener('click',()=>{state.id.name='LXST-'+Math.random().toString(16).slice(2,6).toUpperCase();localStorage.setItem(KEY,JSON.stringify(state.id));$('#idname').textContent=state.id.name;});
$('#btn-newid').addEventListener('click',async()=>{localStorage.removeItem(KEY);state.id=await loadIdentity();$('#call').textContent=shortHash(state.id.hash);$('#fullhash').textContent=state.id.hash;$('#idname').textContent=state.id.name;state.stations=seedGhosts(state.id.hash);state.mesh?.close();state.mesh=createMesh(state.id.hash);log('new station '+shortHash(state.id.hash));});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installEvt=e;$('#banner').hidden=false;});
$('#btn-install').addEventListener('click',async()=>{await state.installEvt?.prompt();$('#banner').hidden=true;});
resizeRadar();window.addEventListener('resize',resizeRadar);const loop=()=>{state.sweep+=0.025;drawRadar();requestAnimationFrame(loop);};requestAnimationFrame(loop);}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
main();
